// Crediti provvisori del gioco: un elenco lunghissimo di ruoli da film, tutti coperti dalle stesse tre persone.
// È uno scherzo per il periodo di lavorazione ("Work in progress"): i crediti veri si scrivono a fine gioco.
// Il menu iniziale li fa scorrere dal basso verso l'alto nella schermata Crediti.
// I ruoli sono in italiano e in inglese: con le altre lingue si vedono in inglese.
// Per aggiungere un ruolo: una riga nell'elenco qui sotto (ruolo in italiano, ruolo in inglese, nomi).
// Come montarlo: non si monta su nessun oggetto, lo usa MenuPrincipale.
public static class TestiCrediti
{
    public static readonly (string it, string en, string nomi)[] Elenco =
    {
        ("Regia", "Directed by", "Giuseppe"),
        ("Sceneggiatura", "Screenplay", "Giuseppe"),
        ("Aiuto regia", "Assistant director", "Lorenzo"),
        ("Aiuto dell'aiuto regia", "Assistant to the assistant director", "Nazar"),
        ("Specialista luci ed effetti sul set", "On-set lighting and effects specialist", "Nazar"),
        ("Riprese subacquee", "Underwater cinematography", "Lorenzo"),
        ("Riprese aeree con il drone", "Aerial drone footage", "Giuseppe"),
        ("Sommozzatore del Lago Nero", "Black Lake diver", "Lorenzo"),
        ("Fonico del \"plof\" del lago", "Sound of the lake's \"plop\"", "Giuseppe"),
        ("Guardiano del molo", "Pier keeper", "Nazar"),
        ("Capitano delle barchette", "Rowboat captain", "Giuseppe"),
        ("Mozzo delle barchette", "Rowboat deckhand", "Lorenzo"),
        ("Addestratore di orchi", "Orc trainer", "Lorenzo"),
        ("Voce dell'orco enorme", "Voice of the huge orc", "Nazar"),
        ("Voce dell'orco enorme (solo le urla)", "Voice of the huge orc (screams only)", "Giuseppe"),
        ("Consulente per i grugniti", "Grunt consultant", "Lorenzo"),
        ("Truccatore degli orchi", "Orc makeup artist", "Nazar"),
        ("Dentista degli orchi", "Orc dentist", "Giuseppe"),
        ("Avvocato dell'orco sgherro", "The orc henchman's lawyer", "Giuseppe"),
        ("Psicologo dell'orco sgherro", "The orc henchman's therapist", "Nazar"),
        ("Controfigura dell'orco enorme", "Huge orc stunt double", "Lorenzo"),
        ("Controfigura del protagonista", "Protagonist's body double", "Nazar"),
        ("Coreografo dei combattimenti", "Fight choreographer", "Giuseppe"),
        ("Insegnante di parata, schivata e attacco", "Parry, dodge and attack instructor", "Giuseppe"),
        ("Maestro di esecuzioni furtive", "Stealth execution master", "Lorenzo"),
        ("Contabile dei colpi critici", "Critical hit accountant", "Lorenzo"),
        ("Affilatore di asce", "Axe sharpener", "Lorenzo"),
        ("Fabbro di scena", "Prop blacksmith", "Nazar"),
        ("Lucidatore di scudi", "Shield polisher", "Giuseppe"),
        ("Parrucchiere del druido", "The druid's hairdresser", "Giuseppe"),
        ("Barbiere della barba del druido", "The druid's beard stylist", "Lorenzo"),
        ("Stilista della tunica del druido", "The druid's robe designer", "Nazar"),
        ("Responsabile della nebbia", "Head of fog", "Nazar"),
        ("Assistente alla nebbia", "Fog assistant", "Giuseppe"),
        ("Stagista della nebbia", "Fog intern", "Lorenzo"),
        ("Responsabile del buio", "Head of darkness", "Lorenzo"),
        ("Responsabile della luna", "Moon supervisor", "Giuseppe"),
        ("Meteorologo", "Meteorologist", "Lorenzo"),
        ("Cronometrista della notte (50 minuti esatti)", "Night timekeeper (exactly 50 minutes)", "Giuseppe"),
        ("Responsabile del tasto T", "Person in charge of the T key", "Giuseppe"),
        ("Accenditore ufficiale di torce", "Official torch lighter", "Lorenzo"),
        ("Spegnitore ufficiale di torce", "Official torch extinguisher", "Nazar"),
        ("Collocatore di alberi (1672 alberi)", "Tree placer (1,672 trees)", "Lorenzo"),
        ("Contatore degli alberi (ricontati due volte)", "Tree counter (counted twice)", "Nazar"),
        ("Potatore degli alberi secchi", "Dead tree pruner", "Nazar"),
        ("Giardiniere degli orti", "Vegetable garden keeper", "Giuseppe"),
        ("Muratore delle case a schiera", "Terraced house bricklayer", "Nazar"),
        ("Orientatore di porte verso la piazza", "Door orientation specialist", "Giuseppe"),
        ("Ispettore delle strettoie", "Narrow passage inspector", "Lorenzo"),
        ("Collaudatore di trappole a spuntoni", "Spike trap tester", "Lorenzo"),
        ("Infermiere del collaudatore di trappole", "The spike trap tester's nurse", "Nazar"),
        ("Lucidatore di poligoni", "Polygon polisher", "Nazar"),
        ("Contatore di poligoni (ne mancano ancora)", "Polygon counter (still a few missing)", "Lorenzo"),
        ("Addetto alla pixellatura retrò", "Retro pixelation operator", "Giuseppe"),
        ("Tecnico del suono dei passi sull'erba", "Footsteps on grass sound engineer", "Lorenzo"),
        ("Tecnico del suono dei passi sul legno", "Footsteps on wood sound engineer", "Nazar"),
        ("Tecnico del suono dei passi sulla pietra", "Footsteps on stone sound engineer", "Giuseppe"),
        ("Sindaco di Villaggio Lago Nero", "Mayor of Black Lake Village", "Giuseppe"),
        ("Oste della taverna", "Tavern innkeeper", "Lorenzo"),
        ("Cuoco della taverna", "Tavern cook", "Nazar"),
        ("Clienti abituali della taverna", "Tavern regulars", "Giuseppe, Lorenzo, Nazar"),
        ("Custode del cimitero", "Graveyard keeper", "Nazar"),
        ("Campanaro del tempio", "Temple bell ringer", "Lorenzo"),
        ("Domatore di lupi", "Wolf tamer", "Nazar"),
        ("Allevatore di corvi", "Raven breeder", "Lorenzo"),
        ("Traduzione in russo", "Russian translation", "Giuseppe"),
        ("Traduzione in cinese", "Chinese translation", "Lorenzo"),
        ("Traduzione in portoghese", "Portuguese translation", "Nazar"),
        ("Revisore delle virgole", "Comma reviewer", "Giuseppe"),
        ("Cacciatore di quadratini nei caratteri", "Missing glyph hunter", "Nazar"),
        ("Premitore di Fetch origin", "Fetch origin presser", "Giuseppe"),
        ("Premitore di Pull origin", "Pull origin presser", "Nazar"),
        ("Risolutore di conflitti", "Merge conflict resolver", "Lorenzo"),
        ("Addetto al caffè", "Coffee runner", "Lorenzo"),
        ("Addetto al secondo caffè", "Second coffee runner", "Nazar"),
        ("Addetto al terzo caffè", "Third coffee runner", "Giuseppe"),
        ("Catering", "Catering", "Giuseppe, Lorenzo, Nazar"),
        ("Nessun orco è stato maltrattato durante la lavorazione", "No orcs were harmed in the making of this game", ""),
        ("Tranne quelli dell'esecuzione furtiva", "Except the stealth execution ones", "Lorenzo"),
        ("Grazie per aver giocato", "Thanks for playing", "Giuseppe, Lorenzo, Nazar"),
    };

    public static string Ruolo(int i) => Lingua.Indice == 0 ? Elenco[i].it : Elenco[i].en;
}
